services:
  - type: web
    name: civilisation-compass
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18.3.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html